name: 'Setup Python Environment'
description: 'Installs Python dependencies and tools'

runs:
  using: "composite"
  steps:
    - name: Setup Python Environment
      shell: bash
      run: |
        # System deps
        apt-get update
        apt-get install -y --no-install-recommends make gcc curl git nodejs npm

        # Python deps
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Configure Git and Repository
      shell: bash
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git config --global --add safe.directory "${GITHUB_WORKSPACE}"
        git init
        git add .
        git commit -m "Initial commit for pre-commit checks"

    - name: Debug Repository Status
      shell: bash
      run: |
        git status
        git rev-parse --git-dir
        pwd
        ls -la
