name: Code Quality Checks

on: [push]

jobs:
  pre-check:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-python
      - name: Configure Git and Repository
        shell: bash
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          git init
          git add .
          git commit -m "Initial commit for pre-commit checks"

      - name: Debug Repository Status
        shell: bash
        run: |
          git status
          git rev-parse --git-dir
          pwd
          ls -la

      - name: Run linting
        run: make lint

      - name: Run type checking
        run: make type_check
