name: Code Quality Checks

on: [push]
jobs:
  pre-check:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends make gcc curl git nodejs npm

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r ../requirements-dev.txt

      - name: Run linting
        run: make lint

      - name: Run type checking
        run: make type_check
