name: Code Quality Checks

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  pre-check:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-python

      - name: Run linting
        run: make lint

      - name: Run type checking
        run: make type_check
